# Generated by Django 5.2.4 on 2025-08-05 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(help_text='Symbol used to get price from Binance', max_length=20, unique=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_day_change', models.FloatField(blank=True, help_text='Daily change percentage (can be positive or negative)', null=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencySubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.DecimalField(blank=True, decimal_places=8, help_text='Alert when price goes below this value', max_digits=20, null=True)),
                ('ceiling', models.DecimalField(blank=True, decimal_places=8, help_text='Alert when price goes above this value', max_digits=20, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='cryptocurrency.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency Subscription',
                'verbose_name_plural': 'Currency Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
